version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: topico_user
      POSTGRES_PASSWORD: Wu7LtwbqSbQy75NJDEhJOMoZ2smzZW3b
      POSTGRES_DB: topico
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_queue
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "mi_password_super_seguro"]

volumes:
  postgres_data:
